
export const  INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";

export const RESET="RESET";

export const Product="GETPRODUCT";

export  const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';
